GET http://localhost:5098/games


###
GET http://localhost:5098/games/1


 ###
POST http://localhost:5098/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}


###
PUT http://localhost:5098/games/1
Content-Type: application/json

{
    "name": "EFootball",
    "genre": "War",
    "price": 9.99,
    "releaseDate": "2015-07-17"
}